In [1]:
print('hello world')

hello world


In [1]:
a=1 
type(a)

int

In [2]:
a

1

In [3]:
a,b=True, False 
a and b 

False

In [4]:
a or b 

True

In [7]:
name = "Payel"
"a" in name

True

In [8]:
"b" in name 

False

In [9]:
"A" in name 

False

In [10]:
"b" not in name 

True

In [11]:
if(True):
    print('Intended code')

Intended code


In [12]:
a = [1,2,3,4]
print(a)

[1, 2, 3, 4]


In [13]:
a = ["mango", 34, "girl", 5.]
print(a)

['mango', 34, 'girl', 5.0]


In [14]:
type(a)

list

In [15]:
print(a[0])

mango


In [16]:
print(2*a)

['mango', 34, 'girl', 5.0, 'mango', 34, 'girl', 5.0]


In [17]:
1 in a 

False

In [19]:
b = "i am a girl"
len(b)

11

In [24]:
c = b[::-1]  #reverse a string 
print(c)

lrig a ma i


In [25]:
#The slice statement [::-1] is the same as [11:0:-1] which means start at position 11 , end at position 0, move with the step -1, 
#which means one step backwards. 

In [26]:
a = [i for i in range(100)]

In [27]:
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [29]:
a = [i for i in range(10,100)]
print(a)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [31]:
a = [ i for i in range(0,100,2)]  #print even numbers 
print(a)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [32]:
a= [i for i in range(1,100,2)] #print odd numbers
print(a)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [33]:
# Immutable list = tuple 
a = (1,2,3)
type(a)

tuple

In [34]:
a = {1,2,3}
type(a)

set

In [36]:
a = { 24 : "apple"}
a[24]


'apple'

In [37]:
a['fruit'] = 24
print(a)

{24: 'apple', 'fruit': 24}


In [38]:
# this shows set is mutable . We can edit the set 

In [40]:
#using numpy for array manipulation
import numpy as np

In [41]:
a = np.array([1,2],[3,4])
print(a)

TypeError: data type not understood

In [42]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [44]:
#minimum dimensions 
a = np.array([1,2,3,4], ndmin =2)
print(a)

[[1 2 3 4]]


In [45]:
a = np.array([1,2,3,4], ndmin =3)
print(a)

[[[1 2 3 4]]]


In [46]:
# dtype parameter 
a = np.array([1,2,3,4], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [51]:
#shape of the array 
a = np.array([[1,2,3,4],[5,6,7,8]])
a.shape    #2 rows and 4 columns 


(2, 4)

In [52]:
#reshaping the array 
a = np.array([[1,2,3,4],[5,6,7,8]])
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [58]:
a= np.arange(24)  # same as a = [i for i in range(24)]
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [59]:
# find the dimension of a 
a.ndim

1

In [60]:
# changing the shape of the array 
a.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [61]:
# using pandas for data preprocessing 
import pandas as pd 


In [62]:
s= pd.Series()
print(s)

Series([], dtype: float64)


In [63]:
data = np.array([1,2,3,4,5])
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [66]:
pd.Series(data, index = [100,101,102,103,104])

100    1
101    2
102    3
103    4
104    5
dtype: int32

In [67]:
data = {'a':1., 'b':2., 'c': 4.}
s = pd.Series(data)
print(s)

a    1.0
b    2.0
c    4.0
dtype: float64


In [68]:
s = pd.Series(data, index=['d','c','b'])
print(s)

d    NaN
c    4.0
b    2.0
dtype: float64


In [69]:
s = pd.Series(5, index=['a','b','c','d'])
print(s)

a    5
b    5
c    5
d    5
dtype: int64


In [70]:
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
s[1]

2

In [71]:
s[-3:]

c    3
d    4
e    5
dtype: int64

In [72]:
# DataFrame is a 2-D data structure in form of columns and rows 
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [73]:
df=pd.read_csv("C:\\Users\\GQPF6681\\Desktop\\ML_data.csv")
df

height  weight
0     171      78
1     163      68
2     168      56

In [74]:
# create dataframes from list 
data = [1,2,3,4,5]
s = pd.DataFrame(data)
s

0
0  1
1  2
2  3
3  4
4  5

In [75]:
# create dataframes from set
data = {'Name':['Tom','Ricky','Sally','John'], 'Age':[23,28,21,27]}
s=pd.DataFrame(data)
s

Name  Age
0    Tom   23
1  Ricky   28
2  Sally   21
3   John   27

In [77]:
s=pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
s

Name  Age
rank1    Tom   23
rank2  Ricky   28
rank3  Sally   21
rank4   John   27

In [82]:
# using sklean 
from sklearn import tree
features = [[140,1], [130,1], [150,0], [170,0]]
labels=[0,0,1,1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(features,labels)
print(clf.predict([[150,0]])) 

[1]


In [1]:
#in the above classification example, we have a table of mango and apple and their respective weights and colors(yellow(0) and red(1)). 
#we have a feature list named as "features"
#we give labels to the fruits as mango = 1 and apple  = 0 
#Then we used Decision Tree Classifier 
# we have fit the model using features and labels 
# then by giving a test data that is [150,0], we predict the class of the data it belongs to 